services:
  postgres:
    image: postgres:15-alpine
    container_name: rag_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: financial_rag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    command: >
      mlflow ui
      --backend-store-uri sqlite:////mlruns/mlflow.db
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 5001
      --allowed-hosts "*"
    ports:
      - "5001:5001"
    volumes:
      - mlflow_data:/mlruns  # Prevents loss of your cost & token metrics!
    restart: unless-stopped

  backend:
    build: .
    container_name: rag_backend
    command: uvicorn main2:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
    depends_on:
      - postgres
      - qdrant
      - mlflow
    restart: unless-stopped

  backend_sequential:
    build: .
    container_name: rag_backend_sequential
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
    depends_on:
      - postgres
      - qdrant
      - mlflow
    restart: unless-stopped

  frontend:
    build: .
    container_name: rag_frontend
    command: streamlit run frontend.py --server.port 8501
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped

  scheduler:
    build: .
    container_name: rag_scheduler
    command: python scheduler.py
    volumes:
      - ./sec_data:/app/sec_data
    depends_on:
      - qdrant
      - backend

volumes:
  postgres_data:
  qdrant_data:
  mlflow_data: