services:
  postgres:
    image: postgres:15-alpine
    container_name: rag_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: financial_rag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    command: >
      mlflow ui
      --host 0.0.0.0
      --port 5001
      --allowed-hosts '*'
    ports:
      - "5001:5001"

  backend:
    build: .
    container_name: rag_backend
    command: uvicorn main2:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY} # Added OpenRouter Key
    depends_on:
      - postgres
      - qdrant
      - mlflow

  frontend:
    build: .
    container_name: rag_frontend
    command: streamlit run frontend.py --server.port 8501
    ports:
      - "8501:8501"
    depends_on:
      - backend

  scheduler:
    build: .
    container_name: rag_scheduler
    command: python scheduler.py
    volumes:
      - ./sec_data:/app/sec_data
    depends_on:
      - qdrant

volumes:
  postgres_data:
  qdrant_data: